name: dbt_azure_run

on:
  push:
    branches:
      - main
  workflow_dispatch: # Erlaubt manuelles Starten

jobs:
  run_dbt:
    runs-on: ubuntu-latest


    defaults:
      run:
        working-directory: testdbt

        
    env:
      DBT_AZURE_HOST: ${{ secrets.DBT_AZURE_HOST }}
      DBT_AZURE_USER: ${{ secrets.DBT_AZURE_USER }}
      DBT_AZURE_PWD: ${{ secrets.DBT_AZURE_PWD }}
      DBT_AZURE_DB: ${{ secrets.DBT_AZURE_DB }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Microsoft ODBC Driver (Ubuntu)
        run: |
          # Microsoft Repo hinzuf√ºgen
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          
          # Treiber installieren
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev
          
          # WICHTIG: Sicherstellen, dass die Library-Pfade aktualisiert werden
          sudo ldconfig


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev
          pip install dbt-core==1.8.3 dbt-fabric==1.8.3 dbt-sqlserver==1.8.3

      - name: Run dbt
        run: |
          # Wir nutzen hier kein DYLD_LIBRARY_PATH, da Ubuntu unixodbc direkt findet
          dbt run --profiles-dir .